Models/Order.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASUTask.Models
{
    [Table("Orders")]
    public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Номер")]
        public string Number { get; set; }
        [Display(Name = "Дата")]
        public DateTime Date { get; set; }
        [ForeignKey("Provider")]
        public int ProviderId { get; set; }
        [Display(Name = "Поставщик")]
        public Provider Provider { get; set; }

        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}

Controllers/OrderItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASUTask.Data;
using ASUTask.Models;

namespace ASUTask.Controllers
{
    public class OrderItemsController : Controller
    {
        private readonly AsuDbContext _context;

        public OrderItemsController(AsuDbContext context)
        {
            _context = context;
        }

        // GET: OrderItems
        public async Task<IActionResult> Index()
        {
            var asuDbContext = _context.OrderItems.Include(o => o.Order);
            return View(await asuDbContext.ToListAsync());
        }

        // GET: OrderItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // GET: OrderItems/Create
        public IActionResult Create(int? id)
        {

            //ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Number");
            ViewData["OrderId"] = id;
            return View();
        }

        // POST: OrderItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,Name,Quantity,Unit")] OrderItem orderItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderItem);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Details", "Orders", new { id = orderItem.OrderId });
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Number", orderItem.OrderId);
            return View(orderItem);
        }

        // GET: OrderItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems.FindAsync(id);
            if (orderItem == null)
            {
                return NotFound();
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Number", orderItem.OrderId);
            return View(orderItem);
        }

        // POST: OrderItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrderId,Name,Quantity,Unit")] OrderItem orderItem)
        {
            if (id != orderItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderItemExists(orderItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Number", orderItem.OrderId);
            return View(orderItem);
        }

        // GET: OrderItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // POST: OrderItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderItem = await _context.OrderItems.FindAsync(id);
            _context.OrderItems.Remove(orderItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderItemExists(int id)
        {
            return _context.OrderItems.Any(e => e.Id == id);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASUTask.Data;
using ASUTask.Models;
using ASUTask.ViewModels;
using System.Collections;

namespace ASUTask.Controllers
{
    public class OrdersController : Controller
    {
        private readonly AsuDbContext _context;

        public OrdersController(AsuDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public IActionResult Index(DateTime? startDate, DateTime? endDate, int? provider, int? orderNumber)
        {
            if (startDate == null && endDate == null)
            {
                startDate = DateTime.Now.AddMonths(-1);
                endDate = DateTime.Now;
            }
            

            var orders = _context.Orders
                .Where(x => x.Date > startDate && x.Date < endDate).Include(o => o.Provider)
                .ToList();



            if (provider != null && provider != 0)
            {
                orders = orders.Where(p => p.ProviderId == provider).ToList();
            }
            if (orderNumber != null && orderNumber != 0)
            {
                orders = orders.Where(p => p.Id == orderNumber).ToList();
            }

            List<Provider> providers = _context.Providers.ToList();
            providers.Insert(0, new Provider { Name = "Все", Id = 0 });

            List<Order> orderNumbers = _context.Orders.ToList();
            orderNumbers.Insert(0, new Order { Number = "Все", Id = 0 });

            var viewModel = new OrdersFilter(orders, startDate, endDate);
            viewModel.Providers = new SelectList(providers, "Id", "Name");
            viewModel.OrderNumbers = new SelectList(orderNumbers, "Id", "Number");

            return View(viewModel);
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id, int? name, int? unit)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = new ViewItems();
            viewModel.Order = await _context.Orders
                .Include(o => o.Provider)
                .FirstOrDefaultAsync(m => m.Id == id);
            viewModel.OrderItems = _context.OrderItems.Where(i => i.OrderId == id);


            if (name != null && name != 0)
            {
                viewModel.OrderItems = viewModel.OrderItems.Where(p => p.Id == name).ToList();
            }if (unit != null && unit != 0)
            {
                viewModel.OrderItems = viewModel.OrderItems.Where(p => p.Id == unit).ToList();
            }


            List<OrderItem> orderItems = _context.OrderItems.Where(i => i.OrderId == id).ToList();
            orderItems.Insert(0, new OrderItem { Name = "Все", Id = 0 });

            viewModel.Names = new SelectList(orderItems, "Id", "Name");
            viewModel.Units = new SelectList(orderItems, "Id", "Unit");

            

/*            var order = await _context.Orders
                .Include(o => o.Provider)
                .FirstOrDefaultAsync(m => m.Id == id);*/
/*            if (order == null)
            {
                return NotFound();
            }*/
            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["ProviderId"] = new SelectList(_context.Providers, "Id", "Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,Date,ProviderId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { order.Id });
            }
            ViewData["ProviderId"] = new SelectList(_context.Providers, "Id", "Id", order.ProviderId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["ProviderId"] = new SelectList(_context.Providers, "Id", "Id", order.ProviderId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,Date,ProviderId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProviderId"] = new SelectList(_context.Providers, "Id", "Id", order.ProviderId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Provider)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

Views/Orders/Create.cshtml
@model ASUTask.Models.Order

@{
    ViewData["Title"] = "Создать";
}

<h1>Создать</h1>

<h4>Заказ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProviderId" class="control-label"></label>
                <select asp-for="ProviderId" class ="form-control" asp-items="ViewBag.ProviderId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Orders/Delete.cshtml
@model ASUTask.Models.Order

@{
    ViewData["Title"] = "Удалить";
}

<h1>Удалить</h1>

<h3>Вы действительно хотите удалить?</h3>
<div>
    <h4>Заказ</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Provider)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Provider.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

Views/Orders/Details.cshtml
@model ASUTask.ViewModels.ViewItems

@{
    ViewData["Title"] = "Подробнее";
}

<h1>Подробнее</h1>

<div>
    <h4>Заказ</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Number)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Provider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Provider.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Order.Id">Редактировать</a> |
    <a asp-action="Delete" asp-route-id="@Model.Order.Id">Редактировать</a> |
    <a asp-action="Index">Назад</a>
</div>
<form method="get">
    <div class="form-horizontal">
        <div class="form-inline">
            <label class="control-label">Наименование: </label>
            <select name="name" class="form-control" asp-items="Model.Names"></select>
        </div>
        <div class="form-inline">
            <label class="control-label">Ед. изм.: </label>
            <select name="unit" class="form-control" asp-items="Model.Units"></select>
        </div>
        <div class="form-group-sm">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Фильтр" class="btn btn-default" /> <span> </span>
            </div>
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Заказ
            </th>
            <th>
                Наименование
            </th>
            <th>
                Количество
            </th>
            <th>
                Ед. измерения
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderItems)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Unit)
                </td>
                <td>
                    <a asp-controller="OrderItems" asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                    <a asp-controller="OrderItems" asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                    <a asp-controller="OrderItems" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="OrderItems" asp-action="Create" asp-route-id="@Model.Order.Id">Добавить элемент</a>

Views/Orders/Edit.cshtml
@model ASUTask.Models.Order

@{
    ViewData["Title"] = "Редактировать";
}

<h1>Редактировать</h1>

<h4>Заказ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProviderId" class="control-label"></label>
                <select asp-for="ProviderId" class="form-control" asp-items="ViewBag.ProviderId"></select>
                <span asp-validation-for="ProviderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href='javascript:history.go(-1)'>Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Orders/Index.cshtml
@model ASUTask.ViewModels.OrdersFilter

@{
    ViewData["Title"] = "Заказы";
}

<h1>Заказы</h1>

<p>
    <a asp-action="Create">Создать</a>
</p>
<form method="get">
    <div class="form-horizontal">
        <div class="form-group form-group-sm">
            <div class="col-md-8">
                <input asp-for="@Model.StartDate" class="form-control" />
            </div>
        </div>
        <div class="form-group form-group-sm">
            <div class="col-md-8">
                <input asp-for="@Model.EndDate" class="form-control" />
            </div>
        </div>
        <div class="form-inline">
            <label class="control-label">Поставщик: </label>
            <select name="provider" class="form-control" asp-items="Model.Providers"></select>
        </div>
        <div class="form-inline">
            <label class="control-label">Номер заказа: </label>
            <select name="orderNumber" class="form-control" asp-items="Model.OrderNumbers"></select>
        </div>
        <div class="form-group-sm">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Фильтр" class="btn btn-default" /> <span> </span>
            </div>
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Order.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.Provider)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Orders) {
        <tr onclick="location.href = '@(Url.Action("Details", "Orders", new { item.Id }))'">
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Provider.Name)
            </td>
            <td>
            </td>
        </tr>
}
    </tbody>
</table>